using System;

namespace NexPlugin
{
	public static class Matchmake
	{
		public enum MatchmakeGeoIpResult
		{
			MATCHMAKE_GEO_IP_RESULT_INVALID = 0,
			MATCHMAKE_GEO_IP_RESULT_FOUND = 1,
			MATCHMAKE_GEO_IP_RESULT_NOT_FOUND = 2,
			MATCHMAKE_GEO_IP_RESULT_UNUSED = 3
		}

		public enum MatchmakeSystemType
		{
			MATCHMAKE_SYSTEM_TYPE_INVALID = 0,
			MATCHMAKE_SYSTEM_TYPE_ANYBODY = 1,
			MATCHMAKE_SYSTEM_TYPE_PERSISTENT_GATHERING = 5
		}

		public enum MatchmakeSelectionMethod
		{
			MATCHMAKE_SELECTION_METHOD_RANDOM = 0,
			MATCHMAKE_SELECTION_METHOD_NEAREST_NEIGHBOR = 1,
			MATCHMAKE_SELECTION_METHOD_BROADEN_RANGE = 2,
			MATCHMAKE_SELECTION_METHOD_PROGRESS_SCORE = 3,
			MATCHMAKE_SELECTION_METHOD_BROADEN_RANGE_WITH_PROGRESS_SCORE = 4,
			MATCHMAKE_SELECTION_METHOD_SCORE_BASED = 5
		}

		[Flags]
		public enum GatheringFlags
		{
			Nothing = 0,
			MigrateOwner = 0x10,
			NoPersistentParticipation = 0x40,
			AllowNoParticipant = 0x80,
			ChangeOwnerByOtherHost = 0x200,
			NotifyParticipationEventsToAllParticipants = 0x400,
			NotifyParticipationEventsToAllParticipantsReproducibly = 0x800
		}

		[Flags]
		public enum MatchmakeSessionOption0 : long
		{
			MATCHMAKE_SESSION_OPTION0_NONE = 0L,
			MATCHMAKE_SESSION_OPTION0_FORCE_AUTOMATCH_DELAY = 1L,
			MATCHMAKE_SESSION_OPTION0_FORCE_AUTOMATCH_NODELAY = 2L
		}

		public enum MatchmakeOption
		{
			MATCHMAKE_OPTION_NONE = 0,
			MATCHMAKE_OPTION_RECORD_LAST_GID_FOR_PARTICIPATION_CHECK = 1,
			MATCHMAKE_OPTION_RESERVED_1 = 2
		}

		public enum AutoMatchmakeOption
		{
			AUTO_MATCHMAKE_OPTION_NONE = 0,
			AUTO_MATCHMAKE_OPTION_RECORD_LAST_GID_FOR_PARTICIPATION_CHECK = 1,
			AUTO_MATCHMAKE_OPTION_UNIQUE_GATHERING_BY_CODEWORD = 2
		}

		public enum JoinMatchmakeSessionBehavior
		{
			JOIN_MATCHMAKE_SESSION_BEHAVIOR_JOIN_MYSELF = 0,
			JOIN_MATCHMAKE_SESSION_BEHAVIOR_IM_ALREADY_JOINED = 1
		}

		[Flags]
		public enum FindMatchmakeSessionResultOption
		{
			FIND_MATCHMAKESESSION_RESULT_OPTION_NONE = 0,
			FIND_MATCHMAKESESSION_RESULT_OPTION_APPLICATION_BUFFER = 1,
			FIND_MATCHMAKESESSION_RESULT_OPTION_MATCHMAKE_PARAM = 2
		}

		public enum PersistentGatheringType
		{
			Open = 0,
			PasswordLocked = 1,
			Official = 2
		}

		[Flags]
		public enum MatchmakeSessionModificationFlag
		{
			MATCHMAKE_SESSION_MODIFICATION_FLAG_NONE = 0,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_ATTRIBUTES = 1,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_OPEN_PARTICIPATION = 2,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_APPLICATION_BUFFER = 4,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_PROGRESS_SCORE = 8,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_OPTION0 = 0x10,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_MATCHMAKE_PARAM = 0x20,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_MATCHMAKE_PARAM_OVERRIDE = 0x40,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_STARTED_TIME = 0x80,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_USER_PASSWORD = 0x100,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_GAME_MODE = 0x200,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_DESCRIPTION = 0x400,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_MIN_PARTICIPANTS = 0x800,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_MAX_PARTICIPANTS = 0x1000,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_MATCHMAKE_SYSTEM_TYPE = 0x2000,
			MATCHMAKE_SESSION_MODIFICATION_FLAG_CODEWORD = 0x4000
		}

		public enum AnybodyParticipationPolicyArgument
		{
			WithoutClose = 0,
			CloseOnOwnerMigration = 1
		}

		public const uint INVALID_GATHERINGID = 0u;

		public const uint NUM_MATCHMAKE_SESSION_ATTRIBUTES = 6u;

		public const uint MATCHMAKE_SESSION_NEAREST_NEIGHBOR_ATTRIBUTE_INDEX = 1u;

		public const uint MATCHMAKE_SESSION_BROADEN_RANGE_ATTRIBUTE_INDEX = 1u;

		public const ulong INVALID_PERSISTENT_GATHERING_CODE = 0uL;

		public const uint PERSISTENT_GATHERING_CREATION_MAX = 4u;

		public const uint PERSISTENT_GATHERING_PARTICIPATION_MAX = 16u;

		public const ulong PERSISTENT_GATHERING_CHAT_PARTICIPANTS_MAX = 32uL;

		public const uint SETATTIBUTE_VECTOR_SIZE_MAX = 100u;

		public const byte MAX_PROGRESS_SCORE = 100;

		public const uint UPDATE_PROGRESS_SCORE_MINIMUM_INTERVAL_TIME = 30u;

		public const uint MAX_MATCHMAKE_SESSION_USER_PASSWORD_LENGTH = 32u;

		public const uint MATCHMAKE_SESSION_SYSTEM_PASSWORD_LENGTH = 16u;

		public const uint MAX_MATCHMAKE_BROWSE_SIZE = 100u;

		public const uint MAX_PRINCIPALID_SIZE_TO_FIND_MATCHMAKE_SESSION = 300u;

		public const uint MAX_MATCHMAKE_BROWSE_SIZE_BY_PARTICIPANT = 300u;

		public const uint MAX_MATCHMAKE_SESSION_BY_PARTICIPANT = 1000u;

		public const uint MAX_EXTRA_PARTICIPANTS = 4u;

		public const uint MAX_P2P_SIGNATURE_KEY_LEN = 32u;

		public const ulong RESULTRANGE_ANY_OFFSET = 4294967295uL;

		public const uint MATCHMAKE_STRING_MAX_LENGTH = 256u;

		public const uint MATCHMAKE_BUFFER_MAX_LENGTH = 512u;
	}
}
